version: "3"
services:
  coursematerial:
    image: jakousa/docker-hy
    ports:
      - 4000:80
    container_name: coursematerial
    labels: 
        - com.centurylinklabs.watchtower.enable="true"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --label-enable
