version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.2.3
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: laurihakala/dockerpipeline
          tag: 'latest'
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
